{"name": "test2_login_with_error_password", "status": "passed", "attachments": [{"name": "stdout", "source": "2c471e4f-e79a-49af-80c0-776c346e165a-attachment.txt", "type": "text/plain"}], "start": 1689820318072, "stop": 1689820332767, "uuid": "2413a3a9-5a0f-4dba-b463-f54cc528964b", "historyId": "b63947ce1f51a1679554edf642e2875b", "testCaseId": "b63947ce1f51a1679554edf642e2875b", "fullName": "testcase.login_logout.test_login_with_wrong_info.TestErrorLogin#test2_login_with_error_password", "labels": [{"name": "story", "value": "login with error password"}, {"name": "feature", "value": "Login error"}, {"name": "parentSuite", "value": "testcase.login_logout"}, {"name": "suite", "value": "test_login_with_wrong_info"}, {"name": "subSuite", "value": "TestErrorLogin"}, {"name": "host", "value": "Joys-MacBook-Pro.local"}, {"name": "thread", "value": "8623-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.login_logout.test_login_with_wrong_info"}]}