{"name": "test2_login_with_error_password", "status": "passed", "attachments": [{"name": "stdout", "source": "879b58a6-962b-4512-aa76-5d722840e9f9-attachment.txt", "type": "text/plain"}], "start": 1689847723661, "stop": 1689847737458, "uuid": "3f2a8e3e-a6fe-4000-95bb-bff295fcf231", "historyId": "b63947ce1f51a1679554edf642e2875b", "testCaseId": "b63947ce1f51a1679554edf642e2875b", "fullName": "testcase.login_logout.test_login_with_wrong_info.TestErrorLogin#test2_login_with_error_password", "labels": [{"name": "story", "value": "login with error password"}, {"name": "severity", "value": "minor"}, {"name": "feature", "value": "Login error"}, {"name": "parentSuite", "value": "testcase.login_logout"}, {"name": "suite", "value": "test_login_with_wrong_info"}, {"name": "subSuite", "value": "TestErrorLogin"}, {"name": "host", "value": "Joys-MacBook-Pro.local"}, {"name": "thread", "value": "45895-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.login_logout.test_login_with_wrong_info"}]}