{"name": "test2_login_with_error_password", "status": "passed", "attachments": [{"name": "stdout", "source": "9d37bd86-b5c3-4632-82b4-d30f32e5284e-attachment.txt", "type": "text/plain"}], "start": 1689846814134, "stop": 1689846827931, "uuid": "1fa1825b-d416-4418-afe8-56c95b5ba98e", "historyId": "b63947ce1f51a1679554edf642e2875b", "testCaseId": "b63947ce1f51a1679554edf642e2875b", "fullName": "testcase.login_logout.test_login_with_wrong_info.TestErrorLogin#test2_login_with_error_password", "labels": [{"name": "story", "value": "login with error password"}, {"name": "severity", "value": "minor"}, {"name": "feature", "value": "Login error"}, {"name": "parentSuite", "value": "testcase.login_logout"}, {"name": "suite", "value": "test_login_with_wrong_info"}, {"name": "subSuite", "value": "TestErrorLogin"}, {"name": "host", "value": "Joys-MacBook-Pro.local"}, {"name": "thread", "value": "42392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.login_logout.test_login_with_wrong_info"}]}